In [2]:
import torch, ppgs

phonemes_set = ppgs.data.Dataset('charsiu', features=['phonemes'])
count = len(phonemes_set)

device = 'cuda:3'

totals = torch.zeros(40, dtype=torch.long).to(device)

for i, (phone_tensor,) in enumerate(phonemes_set):
    if i % 10000 == 0:
        print(i, flush=True)
    totals.scatter_add_(dim=0, index=phone_tensor.to(device), src=torch.ones(phone_tensor.shape, dtype=torch.long).to(device))

using cached metadata
preparing dataset metadata (operation may be slow)
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000


In [3]:
torch.save(totals, 'phone_counts.pt')

In [14]:
ratios = totals / totals.sum()
print(ratios)
weights = 1/ratios
print(weights)
weights /= weights.max()
print(weights)

tensor([0.0116, 0.0172, 0.0621, 0.0093, 0.0045, 0.0132, 0.0087, 0.0040, 0.0221,
        0.0117, 0.0154, 0.0224, 0.0142, 0.0123, 0.0042, 0.0083, 0.0327, 0.0257,
        0.0047, 0.0234, 0.0296, 0.0172, 0.0466, 0.0061, 0.0110, 0.0010, 0.0128,
        0.0255, 0.0414, 0.0076, 0.0359, 0.0025, 0.0011, 0.0096, 0.0097, 0.0090,
        0.0036, 0.0275, 0.0004, 0.3741], device='cuda:3')
tensor([  86.4804,   58.1777,   16.1084,  107.6004,  223.3376,   75.9555,
         115.4388,  247.6422,   45.2568,   85.2505,   65.0828,   44.5462,
          70.2477,   81.2414,  236.7241,  120.4397,   30.5476,   38.8798,
         212.6821,   42.6530,   33.7982,   58.2183,   21.4670,  162.8969,
          90.5105,  963.1365,   78.4187,   39.2893,   24.1366,  132.2458,
          27.8339,  401.1130,  888.6804,  104.2947,  102.7537,  111.1952,
         279.5505,   36.4130, 2370.1804,    2.6729], device='cuda:3')
tensor([0.0365, 0.0245, 0.0068, 0.0454, 0.0942, 0.0320, 0.0487, 0.1045, 0.0191,
        0.0360, 0.0275, 0.01

In [17]:
totals.min()/totals

tensor([0.0365, 0.0245, 0.0068, 0.0454, 0.0942, 0.0320, 0.0487, 0.1045, 0.0191,
        0.0360, 0.0275, 0.0188, 0.0296, 0.0343, 0.0999, 0.0508, 0.0129, 0.0164,
        0.0897, 0.0180, 0.0143, 0.0246, 0.0091, 0.0687, 0.0382, 0.4064, 0.0331,
        0.0166, 0.0102, 0.0558, 0.0117, 0.1692, 0.3749, 0.0440, 0.0434, 0.0469,
        0.1179, 0.0154, 1.0000, 0.0011], device='cuda:3')

In [12]:
ratios = totals / totals.sum()
weights = 1-ratios
weights = torch.softmax(torch.log(weights), dim=0)
weights

tensor([0.0253, 0.0252, 0.0240, 0.0254, 0.0255, 0.0253, 0.0254, 0.0255, 0.0251,
        0.0253, 0.0252, 0.0251, 0.0253, 0.0253, 0.0255, 0.0254, 0.0248, 0.0250,
        0.0255, 0.0250, 0.0249, 0.0252, 0.0244, 0.0255, 0.0254, 0.0256, 0.0253,
        0.0250, 0.0246, 0.0254, 0.0247, 0.0256, 0.0256, 0.0254, 0.0254, 0.0254,
        0.0255, 0.0249, 0.0256, 0.0160], device='cuda:3')

In [9]:
torch.save(weights.cpu(), '/home/cameron/ppgs/ppgs/assets/class_weights_complement.pt')

In [11]:
totals

tensor([  5720802,   8503904,  30712944,   4597912,   2215199,   6513513,
          4285712,   1997791,  10931770,   5803333,   7601663,  11106149,
          7042754,   6089717,   2089932,   4107760,  16195606,  12724798,
          2326182,  11599114,  14637963,   8497975,  23046431,   3037119,
          5466074,    513673,   6308917,  12592162,  20497429,   3741043,
         17774653,   1233411,    556710,   4743648,   4814788,   4449268,
          1769760,  13586819,    208734, 185094121], device='cuda:3')